name: Build and Upload APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Gradle Executable Permissions
        run: chmod +x gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34 
          build-tools: 34.0.0 
          ndk: 26.1.10909125

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Dependencies
        run: ./gradlew dependencies

      - name: Build Project
        run: ./gradlew assembleRelease -x lint # Compile the apk

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk # path of *apk?
          
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
